baseURL = "https://ryanforrester.ca"
languageCode = "en-us"
title = "ryan's game dev blog"
theme = "hugo-book"


disablePathToLower = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    lineNoStart = 1
    lineNos = true
    style = "native"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe = true

[menu]
# [[menu.before]]

[[menu.after]]
  name = "steam"
  url = "https://store.steampowered.com/developer/RyanForrester"
  weight = 10

[[menu.after]]
  name = "twitter"
  url = "https://twitter.com/ryynosaur"
  weight = 10

[params]
    BookTheme = 'dark'
    BookToC = true
    BookComments = false